export const selectors = {
  baseUrl: 'https://www.saucedemo.com',
  homePageImage: '[data-test="primary-header"]',
  headerLogo: '[data-test="secondary-header"]',
  landingPageTitle: 'Swag Labs',
  fadedShortSleeveTshirts: '[data-test="inventory-item-name"]',
  blouse: '[data-test="inventory-item-name"]',
  printedDress: '[data-test="inventory-item-name"]',
  printedDressTwo: '[data-test="inventory-item-name"]',
  printedSummerDress: '[data-test="inventory-item-name"]',
  printedSummerDressTwo: '[data-test="inventory-item-name"]',
  printedChiffonDress: '[data-test="inventory-item-name"]',
  addToCartButton: '[data-test="add-to-cart"]',
  successMessage: '.success-pony',
  cartAddedMessage: '[data-test="shopping-cart-badge"]',
  closeBtn: '[data-test="close-btn"]',
  itemCount: '[data-test="shopping-cart-badge"]',
  productCount: '1',
  colourBlack: '[data-test="color-black"]',
  colourOrange: '[data-test="color-orange"]',
  colourBlue: '[data-test="color-blue"]',
  colourYellow: '[data-test="color-yellow"]',
  imagePicture: '[data-test="inventory-item-img"]',
  colourSelected: '[data-test="selected"]',
  itemSelected: 'selected',
  quantityWanted: '[data-test="quantity"]',
  numberOfItems: '5',
  cart: '[data-test="shopping-cart-link"]',
  totalPrice: '[data-test="total-price"]',
  productPrice: '[data-test="product-price"]',
  checkout: '[data-test="checkout"]',
};
